version: '3.8'
services:
  lunar-zebro:
    build:
      context: ./lunar-zebro
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
